stages:
  - test
  - tag

variables:
  GIT_STRATEGY: clone

test:
  stage: test
  image: golang:1.22
  script:
    - go test ./...
  artifacts:
    reports:
      junit: report.xml

tag:
  stage: tag
  image: alpine:latest
  script:
    - apk add --no-cache git
    - TAG_NAME=$(date +%Y%m%d%H%M%S)
    - git tag $TAG_NAME
    - git push origin $TAG_NAME
  only:
    - main
  dependencies:
    - test